# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
name: Add Label

on:
  issues:
    types: created

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        
        with:
          labels: GSSOC21
